from django.contrib import admin
from . import models

admin.site.register(models.User)
admin.site.register(models.Agency)
admin.site.register(models.AgencyRegistrationRequest)
admin.site.register(models.AgencySettings)
admin.site.register(models.StudentProfile)
admin.site.register(models.AgencyStudent)
admin.site.register(models.University)
admin.site.register(models.Program)
admin.site.register(models.ProgramRequirements)
admin.site.register(models.Pipeline)
admin.site.register(models.PipelineStage)
admin.site.register(models.Application)
admin.site.register(models.StageHistory)
admin.site.register(models.Note)
admin.site.register(models.NoteAttachment)
admin.site.register(models.Document)
admin.site.register(models.DocumentVersion)
admin.site.register(models.DocumentCategory)
admin.site.register(models.ApplicationDocumentLink)
admin.site.register(models.Task)
admin.site.register(models.TaskAttachment)
admin.site.register(models.AutoAssignmentRule)
admin.site.register(models.CommissionStructure)
admin.site.register(models.CommissionRecord)
admin.site.register(models.AuditLog)
admin.site.register(models.EmailLog)
